import { 
  LayoutDashboard, 
  BookOpen, 
  Users, 
  GraduationCap, 
  MessageSquare, 
  Briefcase, 
  BarChart3, 
  Settings 
} from 'lucide-react';

export interface SubModule {
  id: string;
  name: string;
}

export interface ModuleData {
  id: string;
  title: string;
  description: string;
  icon: any; // Lucide icon
  color: string;
  stats: string;
  badge?: string;
  subModules: SubModule[];
}

export const teacherModules: ModuleData[] = [
  {
    id: 'workspace',
    title: 'Dashboard & Workspace',
    description: 'Manage profile, timetable, calendar, and AI workspace.',
    icon: LayoutDashboard,
    color: 'from-blue-500 to-indigo-600',
    stats: '12 Tasks Pending',
    badge: '3 New',
    subModules: [
      { id: 'profile', name: 'My Profile' },
      { id: 'teacher_info', name: 'Teacher Information' },
      { id: 'qualifications', name: 'Qualifications' },
      { id: 'experience', name: 'Experience' },
      { id: 'digital_signature', name: 'Digital Signature' },
      { id: 'calendar', name: 'Calendar' },
      { id: 'notifications', name: 'Notifications' },
      { id: 'tasks', name: 'Tasks' },
      { id: 'timetable', name: 'Timetable' },
      { id: 'quick_actions', name: 'Quick Actions' },
      { id: 'documents', name: 'Documents' },
      { id: 'favorites', name: 'Favorites' },
      { id: 'ai_workspace', name: 'AI Workspace' },
    ]
  },
  {
    id: 'academic',
    title: 'Academic & Classroom',
    description: 'Classes, subjects, lessons, and assignments.',
    icon: BookOpen,
    color: 'from-emerald-400 to-teal-600',
    stats: '5 Classes Today',
    subModules: [
      { id: 'class_management', name: 'Class Management' },
      { id: 'curriculum', name: 'Curriculum' },
      { id: 'homework', name: 'Homework, Assignment & Project' },
      { id: 'study_material', name: 'Study Material' },
      { id: 'online_classes', name: 'Online Classes' },
      { id: 'practical_management', name: 'Practical & Lab Management' },
    ]
  },
  {
    id: 'student_lifecycle',
    title: 'Student Lifecycle Management',
    description: 'Attendance, behavior, portfolios, and health records.',
    icon: Users,
    color: 'from-amber-400 to-orange-500',
    stats: '145 Students',
    badge: 'Attention Needed',
    subModules: [
      { id: 'student_list', name: 'Student List' },
      { id: 'student_profile', name: 'Student Profile' },
      { id: 'attendance', name: 'Attendance' },
      { id: 'period_attendance', name: 'Period Attendance' },
      { id: 'behaviour', name: 'Behaviour' },
      { id: 'discipline', name: 'Discipline' },
      { id: 'counselling', name: 'Counselling' },
      { id: 'health_records', name: 'Health Records' },
      { id: 'student_portfolio', name: 'Student Portfolio' },
      { id: 'learning_progress', name: 'Learning Progress' },
      { id: 'weak_student_detection', name: 'Weak Student Detection' },
      { id: 'gifted_student_tracking', name: 'Gifted Student Tracking' },
      { id: 'parent_details', name: 'Parent Details' },
      { id: 'student_documents', name: 'Student Documents' },
      { id: 'activities', name: 'Activities' },
      { id: 'promotion_recommendation', name: 'Promotion Recommendation' },
      { id: 'house_management', name: 'House Management' },
      { id: 'club_management', name: 'Club Management' },
    ]
  },
  {
    id: 'examination',
    title: 'Examination & Assessment',
    description: 'Schedules, marks, online exams, and AI evaluation.',
    icon: GraduationCap,
    color: 'from-purple-500 to-pink-600',
    stats: '2 Upcoming Exams',
    subModules: [
      { id: 'exam_schedule', name: 'Exam Schedule' },
      { id: 'unit_tests', name: 'Unit Tests' },
      { id: 'quiz', name: 'Quiz' },
      { id: 'assignments_exam', name: 'Assignments' },
      { id: 'practical', name: 'Practical' },
      { id: 'viva', name: 'Viva' },
      { id: 'omr_exams', name: 'OMR Exams' },
      { id: 'online_exams', name: 'Online Exams' },
      { id: 'marks_entry', name: 'Marks Entry' },
      { id: 'grade_book', name: 'Grade Book' },
      { id: 'auto_evaluation', name: 'Auto Evaluation' },
      { id: 'ai_evaluation', name: 'AI Evaluation' },
      { id: 'rubrics', name: 'Rubrics' },
      { id: 'competency_assessment', name: 'Competency Assessment' },
      { id: 'blooms_taxonomy', name: "Bloom's Taxonomy" },
      { id: 'result_analysis', name: 'Result Analysis' },
      { id: 'report_cards', name: 'Report Cards' },
      { id: 'performance_prediction', name: 'Performance Prediction' },
    ]
  },
  {
    id: 'communication',
    title: 'Communication & Collaboration',
    description: 'Chats, notices, meetings, and forums.',
    icon: MessageSquare,
    color: 'from-cyan-400 to-blue-500',
    stats: '8 Unread Msgs',
    badge: 'New',
    subModules: [
      { id: 'student_chat', name: 'Student Chat' },
      { id: 'parent_chat', name: 'Parent Chat' },
      { id: 'teacher_chat', name: 'Teacher Chat' },
      { id: 'staff_chat', name: 'Staff Chat' },
      { id: 'announcements', name: 'Announcements' },
      { id: 'circulars', name: 'Circulars' },
      { id: 'notice_board', name: 'Notice Board' },
      { id: 'email', name: 'Email' },
      { id: 'sms', name: 'SMS' },
      { id: 'push_notifications', name: 'Push Notifications' },
      { id: 'whatsapp', name: 'WhatsApp' },
      { id: 'video_meetings', name: 'Video Meetings' },
      { id: 'ptm_scheduler', name: 'PTM Scheduler' },
      { id: 'feedback', name: 'Feedback' },
      { id: 'discussion_forum', name: 'Discussion Forum' },
      { id: 'voice_messages', name: 'Voice Messages' },
      { id: 'polls', name: 'Polls' },
      { id: 'surveys', name: 'Surveys' },
      { id: 'file_sharing', name: 'File Sharing' },
    ]
  },
  {
    id: 'productivity',
    title: 'Productivity & Workflow',
    description: 'Leave, tasks, diary, and workflow automation.',
    icon: Briefcase,
    color: 'from-rose-400 to-red-500',
    stats: 'Leave Balance: 4',
    subModules: [
      { id: 'leave_management', name: 'Leave Management' },
      { id: 'leave_requests', name: 'Leave Requests' },
      { id: 'teacher_attendance', name: 'Teacher Attendance' },
      { id: 'daily_diary', name: 'Daily Diary' },
      { id: 'work_log', name: 'Work Log' },
      { id: 'task_management', name: 'Task Management' },
      { id: 'to_do_list', name: 'To-Do List' },
      { id: 'calendar_prod', name: 'Calendar' },
      { id: 'meeting_scheduler', name: 'Meeting Scheduler' },
      { id: 'reminder', name: 'Reminder' },
      { id: 'substitute_teacher', name: 'Substitute Teacher' },
      { id: 'period_swap', name: 'Period Swap' },
      { id: 'workflow_automation', name: 'Workflow Automation' },
      { id: 'notes', name: 'Notes' },
      { id: 'document_manager', name: 'Document Manager' },
      { id: 'digital_signature_prod', name: 'Digital Signature' },
      { id: 'ai_assistant', name: 'AI Assistant' },
      { id: 'personal_workspace', name: 'Personal Workspace' },
    ]
  },
  {
    id: 'reports',
    title: 'Reports & Analytics',
    description: 'AI insights, class analytics, and custom reports.',
    icon: BarChart3,
    color: 'from-violet-500 to-purple-600',
    stats: '2 New Reports',
    subModules: [
      { id: 'attendance_reports', name: 'Attendance Reports' },
      { id: 'homework_reports', name: 'Homework Reports' },
      { id: 'assignment_reports', name: 'Assignment Reports' },
      { id: 'exam_reports', name: 'Exam Reports' },
      { id: 'performance_reports', name: 'Performance Reports' },
      { id: 'subject_analytics', name: 'Subject Analytics' },
      { id: 'class_analytics', name: 'Class Analytics' },
      { id: 'teacher_analytics', name: 'Teacher Analytics' },
      { id: 'student_analytics', name: 'Student Analytics' },
      { id: 'ai_insights', name: 'AI Insights' },
      { id: 'weak_topic_analysis', name: 'Weak Topic Analysis' },
      { id: 'topper_analysis', name: 'Topper Analysis' },
      { id: 'predictive_analytics', name: 'Predictive Analytics' },
      { id: 'charts', name: 'Charts' },
      { id: 'graphs', name: 'Graphs' },
      { id: 'custom_reports', name: 'Custom Reports' },
      { id: 'export_pdf', name: 'Export PDF' },
      { id: 'export_excel', name: 'Export Excel' },
      { id: 'print', name: 'Print' },
    ]
  },
  {
    id: 'settings',
    title: 'Settings & Security',
    description: 'Profile, preferences, 2FA, and integrations.',
    icon: Settings,
    color: 'from-slate-600 to-slate-800',
    stats: 'System Secured',
    subModules: [
      { id: 'profile_settings', name: 'Profile Settings' },
      { id: 'preferences', name: 'Preferences' },
      { id: 'theme', name: 'Theme' },
      { id: 'language', name: 'Language' },
      { id: 'notification_settings', name: 'Notification Settings' },
      { id: 'password', name: 'Password' },
      { id: '2fa', name: '2FA' },
      { id: 'login_history', name: 'Login History' },
      { id: 'session_management', name: 'Session Management' },
      { id: 'connected_devices', name: 'Connected Devices' },
      { id: 'audit_logs', name: 'Audit Logs' },
      { id: 'role_permissions', name: 'Role Permissions' },
      { id: 'cloud_storage', name: 'Cloud Storage' },
      { id: 'backup', name: 'Backup' },
      { id: 'api_integration', name: 'API Integration' },
      { id: 'google_workspace', name: 'Google Workspace' },
      { id: 'microsoft_365', name: 'Microsoft 365' },
      { id: 'zoom', name: 'Zoom' },
      { id: 'support_center', name: 'Support Center' },
      { id: 'help', name: 'Help' },
      { id: 'logout', name: 'Logout' },
    ]
  }
];
